# Generated by Django 4.2.19 on 2025-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_time", models.DateTimeField(verbose_name="対戦時間")),
                (
                    "my_character",
                    models.CharField(max_length=100, verbose_name="自分のキャラ"),
                ),
                (
                    "opponent_character",
                    models.CharField(max_length=100, verbose_name="相手のキャラ"),
                ),
                ("win_or_loss", models.CharField(max_length=10, verbose_name="勝敗")),
                ("fighting_strength", models.IntegerField(verbose_name="戦闘力")),
            ],
        ),
    ]
