# Generated by Django 4.2.19 on 2025-03-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="GameRecord", new_name="Match",),
    ]
