# Generated by Django 4.2.19 on 2025-03-01 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_rename_gamerecord_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="stage",
            field=models.CharField(
                default="NULL", max_length=100, verbose_name="対戦ステージ"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="対戦時間"
            ),
        ),
    ]
