# Generated by Django 4.2.19 on 2025-03-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_match_stage_alter_match_match_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="stage",
            field=models.CharField(max_length=100, verbose_name="対戦ステージ"),
        ),
    ]
