# Generated by Django 4.2.19 on 2025-03-03 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_alter_match_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
